### ISSUE TITLE
Eddaily Posts Feed: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ednc-2020#119]
`Warning: Invalid argument supplied for foreach() in /Local/ednc/app/public/wp-content/themes/ednc-2020/resources/feeds/eddaily-posts.php on line 39`.

Also, what are these fields referenced in the feed?

```
$subject = get_field('subject_line');
$preview = get_field('preview_text');
$articles = get_field('daily_articles');
```

Related: #88

**Comment by isabisa** [comment]
Whoops, the fields were added but there is still that same PHP error. Reopening to debug again.
