### ISSUE TITLE
Search Icon sized incorrectly on mobile iOS

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ednc-2020#131]
![IMG_6933](https://user-images.githubusercontent.com/6686529/86269548-e8e50380-bb97-11ea-9d2c-25a6d4600f65.PNG)

**Comment by isabisa** [comment]
**Updated Screenshot Attached**
![Screenshot URL](https://live.browserstack.com/issue-tracker/5fb7264898ffcb5aae72b16727afff0fe35b0c00/realios_iPad_Pro_12.9_2018.jpg)

**Comment by andrewmarino** [comment]
Fixed!
