### ISSUE TITLE
Search icon is tiny on iOS

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#135]
**URL tested:** https://ednc.test/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fednc.test%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://ednc.test/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 11 Pro |
| Browser | Mobile_safari |
| Operating System | iOS 13.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in x 2.81 x 5.67 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c4347d35bec990c64985f64b8f0ff263c5ac4f93/realios_iPhone_11_Pro.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c4347d35bec990c64985f64b8f0ff263c5ac4f93/realios_iPhone_11_Pro.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fednc.test%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://ednc.test/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by andrewmarino** [comment]
Duplicate #131.
