### ISSUE TITLE
FacetWP pagination forces user back to the top of the page via #

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ednc-2020#143]
Because FacetWP doesn't have accessible pagination (it omits the # on the anchor and fails validation, keyboards can't use it), adding a # href fixes that issue. However, not ideal because it returns the user to the top of the page in a jarring way. I'd like to update this to smooth scroll a user to the top of the archive loop (and perhaps even force focus the first post, so users know where they are).

**Comment by isabisa** [comment]
Can it jump to top of the section where the facet exists instead?

**Comment by isabisa** [comment]
Take a look at https://www.rtp.org/directory-map/ for how their FWP pagination works.
