### ISSUE TITLE
Is there a way to only search by post title on ACF relationship field?

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#153]
It would be so much easier since they have over 50k posts

**Comment by andrewmarino** [comment]
Yes I believe that is possible.

https://searchwp.com/v3/docs/kb/intercept-advanced-custom-fields-acf-relationship-field-searches/

The implementation might be slightly different since that's a v3 documentation example and things are on v4 now.

**Comment by andrewmarino** [comment]
@isabisa Want to give this one a quick test before we close it out? I've set up a supplemental engine to intercept all search queries on ACF relationship fields. The engine is only set to index post titles, so it should hopefully improve things.

https://edncstaging.wpengine.com/wp-admin/options-general.php?page=searchwp

One thing to note is there are stopwords in the plugin settings which will get ignored—these can be added and removed. Maybe it's something the client can adjust to their liking based on what they find useful.

https://edncstaging.wpengine.com/wp-admin/options-general.php?page=searchwp&tab=settings

**Comment by isabisa** [comment]
Verified this works MUCH better now!
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/928176/87188953-bf298c00-c2bd-11ea-87e8-b1af3c777489.png">
