### ISSUE TITLE
Remove the category/taxonomy description field

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#157]
Want to handle this through ACF instead.

https://wordpress.stackexchange.com/questions/56569/remove-the-category-taxonomy-description-field

**Comment by andrewmarino** [comment]
It looks like the ACF field has been created already.

https://github.com/unitymakesus/ednc-2020/commit/7d904fa4dd5012578bc088f8cc78bc380412dae7#diff-2ea19ed2b3224098272d5e8da4b4ee3b

I'll hide the old field with CSS (rather than jQuery) since we want to avoid any delay in hiding it.

**Comment by isabisa** [comment]
Sounds good!

**Comment by isabisa** [comment]
Fixed in dd50359
