### ISSUE TITLE
Gutenberg: Related Reading Block not showing correct posts

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#159]
[EducationNC’s Annual Report, 2019-20 - EducationNC](https://edncstaging.wpengine.com/annual-report-19-20/)
![image](https://user-images.githubusercontent.com/928176/86645347-520bb300-bfac-11ea-87f7-ba4741ce6f20.png)

**Comment by andrewmarino** [comment]
There's an issue / conflict with blocks (and a lot of confusion on how these were set up in the 2019 theme...). There's actually two blocks with the same name.

* Recommended Articles Block (group_5d54586c0ac62) used on acf\/recommended-articles-inline-block.
* Recommended Articles Block (group_5e0d1d5cbae4d) used on acf\/recommended-articles-block.

recommended-articles-inline-block is currently using the other block's ACF fields, so the values are incorrect. In any case, I think we will need to register and bring over the old block, but maybe we can deprecate or hide it similar to other old blocks? What do you think @isabisa?

**Comment by isabisa** [comment]
LOL of course. I can take this one with the other Gutenberg issue I'm working on.
