### ISSUE TITLE
Weird broken embed on 2017-18 annual report

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#161]
Staging site: 
![image](https://user-images.githubusercontent.com/928176/86645741-ac0c7880-bfac-11ea-8bfe-2d97eed8b744.png)

Live site:
![image](https://user-images.githubusercontent.com/928176/86645769-b0d12c80-bfac-11ea-9824-0392d290cf56.png)

**Comment by andrewmarino** [comment]
Weird! This is loading the correct embed, some kind of Leaflet map. Is this still happening?

**Comment by isabisa** [comment]
They uploaded some HTML file to the media library and then put it in an iframe. The html file just isn't on the staging site's media library. I’m going to change the staging site post to just point to the main site. No action will be needed on this once we launch.
