### ISSUE TITLE
Voices page: Person should only appear if they have published an article

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#174]
Relevant for team members. Some have not published, but they are staff members, so they have a "bio" and are tagged as staff.

**Comment by andrewmarino** [comment]
Is this really a bug? All 13 bios in the Staff term have published something.

**Comment by isabisa** [comment]
Oh maybe it's not a bug. This was just something Nancy mentioned, so I assumed it was happening. I checked their live site and it doesn't look like anyone on there hasn't published. I think we can close this issue for now.

**Comment by andrewmarino** [comment]
Ah I see! Yeah, I mean there is nothing in the site currently that excludes authors / bios in the query if they haven't posted. This would be new if they need that to happen (and I think that query will be expensive to run on each Author / Bio, something to keep in mind).
