### ISSUE TITLE
Chapters shortcode is not working properly

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#181]

**Comment by isabisa** [comment]
Now it doesn't scroll to the chapter when you click on a link in the TOC 🙃

**Comment by andrewmarino** [comment]
We need to add a conditional around that Intersection Observer stuff. It'll throw an error if the element being passed in doesn't exist.

**Comment by isabisa** [comment]
@andrewmarino can you add some z-index to this so the sticky TOC goes behind any full-width content?
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/928176/87193033-cf456980-c2c5-11ea-8909-444455d70df3.png">
