### ISSUE TITLE
Rename Editor's Picks to EdDaily

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#190]
- [x] Home page
- [x] Single post (front-end)
- [x] Archive featured image fallback
- [ ] EdNC to provide new banner and featured image fallback

**Comment by andrewmarino** [comment]
So the verbiage should switch to the following?

* Editor’s Picks for July 3, 2020 -> EdDaily’s for July 3, 2020
* View more Editor’s Picks -> View more EdDaily’s

**Comment by isabisa** [comment]
* Editor’s Picks for July 3, 2020 -> EdDaily for July 3, 2020
* View more Editor’s Picks -> View more EdDaily Posts

**Comment by andrewmarino** [comment]
EdDaily Featured Image Fallback can be added here (along with swapping the existing banner image out).

https://edncstaging.wpengine.com/wp-admin/admin.php?page=acf-options-pages
