### ISSUE TITLE
All authors should have the option to have website, twitter, email links at bottom of article

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#192]
Double check this works!

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/928176/87045496-f74da380-c1c5-11ea-98aa-afaebd5ba670.png">

**Comment by andrewmarino** [comment]
Twitter and Email works, but not website (on the author info template part). Will push up a fix!

**Comment by isabisa** [comment]
Also make sure this works for any author, even someone who is a "contributor."

**Comment by andrewmarino** [comment]
Didn't mean to close this one before having a chance to review further!

**Comment by andrewmarino** [comment]
This indeed works for authors, including Contributors.
