### ISSUE TITLE
Embed links to NCPPR aren't working

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#193]
Nothing happens when you click
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/928176/87046366-1c8ee180-c1c7-11ea-80ed-4aa06a318df8.png">

https://edncstaging.wpengine.com/educationncs-annual-report-2016-17/

**Comment by andrewmarino** [comment]
Issue lies with the external site (likely the same issue EdNC has with overrides to the embed functionality of WP).

**Comment by isabisa** [comment]
Closing for now since we're not dealing with it on this project.
