### ISSUE TITLE
Most Recent: Make byline full-width

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#196]
<img width="277" alt="Screen Shot 2020-07-09 at 9 22 28 AM" src="https://user-images.githubusercontent.com/928176/87047739-dcc8f980-c1c8-11ea-9ccc-1a0e3c755d43.png">

**Comment by andrewmarino** [comment]
The byline is currently full width... but the clear could be adjusted a bit so that it happens closer to the floated elements (on item 2). There's some margin on the Appearance text pushing it down further.
