### ISSUE TITLE
Add featured image fallback to EdDaily on homepage

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#204]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/928176/87187434-28f46680-c2bb-11ea-8018-6d10b94839fc.png">

**Comment by andrewmarino** [comment]
See https://github.com/unitymakesus/ednc-2020/issues/190#issuecomment-656345996

**Comment by isabisa** [comment]
Thanks! Added!
