### ISSUE TITLE
Parallax hero image isn't vertically centered

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#208]
I thought the JS for rellax had set it to center the image. But on staging, it's aligned to the top of its container:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/928176/87203598-f5bcd200-c2d0-11ea-9ba7-29b262c0c568.png">

**Comment by andrewmarino** [comment]
Need to look into positioning it against the wrapping element rather than the body. 

https://github.com/dixonandmoe/rellax#custom-wrapper didn't seem to have any effect.
