### ISSUE TITLE
Template Refresh: Podcast Page

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ednc-2020#41]
- Change CPT
- Includes two main podcasts at the top with subscribe buttons. Links to podcast pages with more information.
- Similar faceted filtering capacity.

**Comment by isabisa** [comment]
- [ ] Archive
- [ ] Term
- [ ] Single

**Comment by isabisa** [comment]
@andrewmarino How do we get the shows to appear at the top of this page? https://edncdev.wpengine.com/podcasts/

**Comment by andrewmarino** [comment]
@isabisa This is handled by a Settings page under Podcasts in the Dashboard menu. (powered by ACF).

**Comment by andrewmarino** [comment]
I've added them in after pushing the adjustments earlier this afternoon. We will probably need a custom image for EdTalk because the banner image used in the default "Taxonomy Image" field isn't ideal for this display.
