### ISSUE TITLE
template-page-team.php

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ednc-2020#58]

**Comment by isabisa** [comment]
* Specialists are not full-time employees but are technically part of team

**Comment by isabisa** [comment]
Let's rename this just `page-team.php`?

**Comment by andrewmarino** [comment]
Sounds good! I also set this up so that it pulls from the taxonomy term used on the Voices page rather than an ACF repeater with manual entry. It's the same content on the Voices page.
