### ISSUE TITLE
page-voices.php

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#70]
Sections will be:
* Team
* Correspondents
* Contributors
* Organizations

Specialists are not full-time employees but are technically part of the team. So combine specialists with team. Combine EdAmbassadors with contributors. Separate organizations who are contributors from contributors.

**Comment by andrewmarino** [comment]
Made a couple of notes for TODOs during launch.

/**
 * TODO: recategorize Specialists as Staff (tax terms).
 * TODO: recategorize Contributor companies as Organizations (tax termps)
 */
