### ISSUE TITLE
page-archive.php

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#80]
Actively used for Archive page (could be handled with an archive template?)

**Comment by andrewmarino** [comment]
Should we revisit with #67 rather than just bring it over 1:1? I agree—this doesn't need to be a traditional page template.

The template uses a WP Query for 5 post types: `'post', 'map', 'ednews', 'edtalk', 'flash-cards'`.

**Comment by andrewmarino** [comment]
This is now being handled with good ol' index.blade.php. I've added a launch item to update the Reading Settings to set that Archive page as the "Posts page".
